
version: '2.1'
services:
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: recorder
      POSTGRES_PASSWORD: redrocer
    healthcheck:
      test: ["CMD","pg_isready"]
      interval: 6s
      timeout: 3s
      retries: 3
  migrate:
    image: 725423950623.dkr.ecr.us-east-1.amazonaws.com/flyway:a250d9950198bc2110f6f57af99c8a6d715a68e1
    volumes:
      - ./flyway:/flyway
    command: ["-url=jdbc:postgresql://db:5432/recorder","migrate"]
    depends_on:
      db:
        condition: service_healthy
  recorder:
    image: recorder
    ports:
      - 8080
    environment:
      RECORDER_DB_HOST: db
      RECORDER_DB_PORT: 5432
      RECORDER_DB_NAME: recorder
      RECORDER_DB_USER: recorder
      RECORDER_DB_PASSWORD: redrocer
    depends_on:
      db:
        condition: service_healthy
